# Site settings
title: Foot & Ankle Specialists of Virginia
description: "Foot and Ankle Specialists of Virginia podiatry practice comprised of Drs. Laurence Rubin, Sonya Faircloth, and Sarah Tammaro."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://footanklespecialistsva.com" # the name of your domain

# Configure sass/scss: https://jekyllrb.com/docs/assets/
sass:
    sass_dir: _scss
    style: compressed

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Foot & Ankle Specialists of Virginia
    hero_description: A trusted, central Virginia practice for over 20 years.

# Testimonials
testimonials:
    testimonials_img: jumping_feet.jpeg

# Map
map:
    zoom: 10

# Footer
copyright: © 2024 Foot & Ankle Specialists of Virginia - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    package-lock.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    README.md,
    webpack.config.js,
    js,

]

# Theme Settings
analytics: UA-53213045-1
google_verification:
